export const INIT_HOME_GALLERY = 'INIT_HOME_GALLERY';
export const GET_HOME_GALLERY = 'GET_HOME_GALLERY';
export const GET_HOME_GALLERY_FAIL = 'GET_HOME_GALLERY_FAIL';

export const INIT_MENU_APPETIZERS = 'INIT_MENU_APPETIZERS';
export const GET_MENU_APPETIZERS = 'GET_MENU_APPETIZERS';
export const GET_MENU_APPETIZERS_FAIL = 'GET_MENU_APPETIZERS_FAIL';